/* Summary: Uses L-system instructions by converting them into 
 *          positions and directions to create room corridors.
 */

using System.Collections.Generic;
using UnityEngine;
public class LSysAlgorithm : MonoBehaviour
{
    public class LSysStep
    {
        public Vector2Int pos;
        public Vector2Int direction;
        public Vector2Int prevDirection;
        public bool directionChanged;
    }
    // Generates the L-system string
    public string GenerateStr(string axiom, string rule, int iterations)
    {
        // Begins with the axiom itself as the L-system's starting point
        string current = axiom;

        // Repeats according to the number of iterations desired
        for (int i = 0; i < iterations; i++)
        {
            string next = "";

            // The following is applied for eacg symbol in the string.
            foreach (char symbol in current)
            {
                // F is replaced with the rule.
                if (symbol == 'F')
                {
                    next += rule;
                }

                // Otherwise, the rest of the symbols remain unchanged.
                else
                {
                    next += symbol;
                }
            }

            // The now-generated string becomes the current string in the next iteration.
            current = next;
        }

        // After all iterations are complete, the final string is returned.
        return current;
    }

    public List<LSysStep> GeneratePath(string ins, Vector2Int start, Vector2Int end)
    {
        List<LSysStep> path = new List<LSysStep>();
        Vector2Int currentPos = start;
        Vector2Int direction;

        if (Mathf.Abs(end.x - start.x) >
           Mathf.Abs(end.y - start.y))
        {

            // Target room is farther away horizontally
            if (start.x < end.x)
            {
                direction = Vector2Int.right;
            }
            else
            {
                direction = Vector2Int.left;
            }
        }
        else
        {
            // / Target room is farther away vertically.
            if (start.y < end.y)
            {
                direction = Vector2Int.up;
            }
            else
            {
                direction = Vector2Int.down;
            }
        }

        // Stores the previous 'F' movement 
        Vector2Int prevDirection = direction;

        // Repeats according the instructions being generated by the system
        foreach (char symbol in ins)
        {

            if (currentPos == end)
            {
                break;
            }

            // F indicates that the corridor moves in the forward direction.
            if (symbol == 'F')
            {
                // Calculate the dist to the target room from the current position.
                Vector2Int targetPoint = end - currentPos;

                /*
                 * Determine the direction to move towards, based on which axis has
                 * a greater distance to the target room
                 */
                if (Mathf.Abs(targetPoint.x) > Mathf.Abs(targetPoint.y))
                {
                    direction = targetPoint.x > 0 ? Vector2Int.right : Vector2Int.left;

                }
                else if (targetPoint.y != 0)
                {
                    direction = targetPoint.y > 0 ? Vector2Int.up : Vector2Int.down;
                }

                // Move one step in the chosen direction
                currentPos += direction;

                bool directionChanged = prevDirection != direction;

                path.Add(new LSysStep
                {
                    pos = currentPos,
                    direction = direction,
                    prevDirection = prevDirection,
                    directionChanged = directionChanged
                });

                prevDirection = direction;


            }
            else if (symbol == '+')
            {
                direction = new Vector2Int(-direction.y, direction.x);
            }

            // Indicates that the current direction rotates 90 degrees, in the opposite direction.
            else if (symbol == '-')
            {
                direction = new Vector2Int(direction.y, -direction.x);
            }
        }

        // Ensuring that the corridor reaches the endpoint  //
        while (currentPos != end)
        {
            Vector2Int prevPos = currentPos;

            // Move horizontally if the x-coordinates differ
            if (currentPos.x != end.x)
            {
                currentPos.x += currentPos.x < end.x ? 1 : -1;
            }

            // Otherwise, move vertically if the y-coordinates differ.
            else
            {
                currentPos.y += currentPos.y < end.y ? 1 : -1;
            }

            Vector2Int moveDirection = currentPos - prevPos;

            path.Add(new LSysStep
            {
                pos = currentPos,
                direction = moveDirection,
                prevDirection = prevDirection,
                directionChanged = false
            });
        }

        return path;
    }
}

